name: CI

on:
  push:
    branches-ignore:
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Sources/

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2 # update to v3
      with:
        dotnet-version: 7.x.x
        include-prerelease: true # remove when v3
        #dotnet-quality: preview # enable when v3
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      id: tests
      run: dotnet test --no-build --verbosity normal
